// <auto-generated />
using System;
using Co2HomeEmissionsTP36.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Co2HomeEmissionsTP36.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240416014354_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Co2HomeEmissionsTP36.Models.Concession", b =>
                {
                    b.Property<int>("ConcessionId")
                        .HasColumnType("int");

                    b.Property<string>("ConcessionName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.HasKey("ConcessionId");

                    b.ToTable("concession");
                });

            modelBuilder.Entity("Co2HomeEmissionsTP36.Models.EmissionFactor", b =>
                {
                    b.Property<int>("FactorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FactorId"));

                    b.Property<int?>("EnergyId")
                        .HasColumnType("int");

                    b.Property<double?>("ScopeOneEmission")
                        .HasColumnType("float");

                    b.Property<double?>("ScopeThreeEmission")
                        .HasColumnType("float");

                    b.Property<double?>("ScopeTwoEmission")
                        .HasColumnType("float");

                    b.HasKey("FactorId");

                    b.HasIndex("EnergyId");

                    b.ToTable("emissionFactor");
                });

            modelBuilder.Entity("Co2HomeEmissionsTP36.Models.Energy", b =>
                {
                    b.Property<int>("EnergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnergyId"));

                    b.Property<double?>("EnergyContentFactor")
                        .HasColumnType("float");

                    b.Property<string>("EnergyName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EnergyId");

                    b.ToTable("energy");
                });

            modelBuilder.Entity("Co2HomeEmissionsTP36.Models.EnergyConsumption", b =>
                {
                    b.Property<int>("ConsumptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsumptionId"));

                    b.Property<double?>("EmissionAmount")
                        .HasColumnType("float");

                    b.Property<int?>("EnergyId")
                        .HasColumnType("int");

                    b.Property<int?>("HouseholdNum")
                        .HasColumnType("int");

                    b.Property<string>("Year")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ConsumptionId");

                    b.HasIndex("EnergyId");

                    b.ToTable("energyConsumption");
                });

            modelBuilder.Entity("Co2HomeEmissionsTP36.Models.Savings", b =>
                {
                    b.Property<int>("SavingsId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CtaUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Duration")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EligibilityRequirements")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Method")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.HasKey("SavingsId");

                    b.HasIndex("CategoryId");

                    b.ToTable("savings");
                });

            modelBuilder.Entity("Co2HomeEmissionsTP36.Models.SavingsCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.HasKey("CategoryId");

                    b.ToTable("category");
                });

            modelBuilder.Entity("Co2HomeEmissionsTP36.Models.SavingsConcession", b =>
                {
                    b.Property<int>("SavingsId")
                        .HasColumnType("int");

                    b.Property<int>("ConcessionId")
                        .HasColumnType("int");

                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.HasKey("SavingsId", "ConcessionId");

                    b.HasIndex("ConcessionId");

                    b.ToTable("savingsConcession");
                });

            modelBuilder.Entity("Co2HomeEmissionsTP36.Models.EmissionFactor", b =>
                {
                    b.HasOne("Co2HomeEmissionsTP36.Models.Energy", "Energy")
                        .WithMany()
                        .HasForeignKey("EnergyId");

                    b.Navigation("Energy");
                });

            modelBuilder.Entity("Co2HomeEmissionsTP36.Models.EnergyConsumption", b =>
                {
                    b.HasOne("Co2HomeEmissionsTP36.Models.Energy", "Energy")
                        .WithMany()
                        .HasForeignKey("EnergyId");

                    b.Navigation("Energy");
                });

            modelBuilder.Entity("Co2HomeEmissionsTP36.Models.Savings", b =>
                {
                    b.HasOne("Co2HomeEmissionsTP36.Models.SavingsCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Co2HomeEmissionsTP36.Models.SavingsConcession", b =>
                {
                    b.HasOne("Co2HomeEmissionsTP36.Models.Concession", "Concession")
                        .WithMany()
                        .HasForeignKey("ConcessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Co2HomeEmissionsTP36.Models.Savings", "Savings")
                        .WithMany()
                        .HasForeignKey("SavingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concession");

                    b.Navigation("Savings");
                });
#pragma warning restore 612, 618
        }
    }
}
